database:
  hostName: 127.0.0.1
  hostPort: 3306
  databaseName: cradlehrm
  privilegedDatabaseUser: root
  privilegedDatabasePassword: root
  useSameDbUserForOrangeHRM: y # y/n, if this field `n` fill `orangehrmDatabaseUser` and `orangehrmDatabasePassword`
  orangehrmDatabaseUser: ~
  orangehrmDatabasePassword: ~
  isExistingDatabase: n # y/n
  enableDataEncryption: n # y/n

organization:
  name: CradleHRM
  country: NGN

admin:
  adminUserName: Admin
  adminPassword: Chrm@1234
  adminEmployeeFirstName: CradleHRM
  adminEmployeeLastName: Admin
  workEmail: admin@example.com
  contactNumber: ~

license:
  agree: y # y/n
